### ISSUE TITLE
Display GO release DOI on Data page

### ISSUE THREAD

**Issue by dustine32** [pantherdb/features-bugs#11]
@mugitty This is for the UI aspect of this ticket https://github.com/pantherdb/fullgo_paint_update/issues/40.

The full GO update is now storing the DOI from the GO release metadata into the fullgo_version table:
![image](https://user-images.githubusercontent.com/2678599/81595897-0f48a880-9378-11ea-95c1-3df9c256c2a2.png)

Would we be able to add this here?
![image](https://user-images.githubusercontent.com/2678599/81596123-63538d00-9378-11ea-908d-faed5d9e6c26.png)
So like:
Gene Ontology (from GO database version 1.2, released 2020-02-21, DOI 10.5281/zenodo.3689211)

**Comment by mugitty** [comment]
@dustine32 , I am wondering if we should be using the GO version column (GO_ANNOTATION_FORMAT_VERSION) to add this information.  Perhaps separate 1.2 with a hyphen and give the go_annotation_doi.  The '1.2' part has not changed yet the date keeps on getting updated and the data keeps on changing.

**Comment by dustine32** [comment]
@mugitty I'd prefer to store them separately since (I'm assuming) they refer to different things.

I'm actually confused what GO_ANNOTATION_FORMAT_VERSION refers to if not the GAF spec version that we parse, which is currently [2.1](http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/). Maybe it's a remnant from GO's MySQL DB days? @huaiyumi Do you know what "1.2" means?

**Comment by mugitty** [comment]
We can store in a separate column.  Perhaps we should remove the 1.2 part (information from GO_ANNOTATION_FORMAT_VERSION)
So we would have something like the following:
(from GO database released 2020-02-21, DOI 10.5281/zenodo.3689211)

**Comment by dustine32** [comment]
@mugitty Yeah that looks great. Though I'm still curious (just curious) what that 1.2 means. Thanks!

**Comment by mugitty** [comment]
@dustine32 , let me know when you have updated the database and I will update the code.

**Comment by dustine32** [comment]
@mugitty Yep, both prod and dev DBs have data in `go_annotation_doi` column now. Thanks!

**Comment by mugitty** [comment]
Released to production
