### ISSUE TITLE
Incomplete data in gene aggregation table for SACS2|EnsemblGenome=SSO3234|UniProtKB=Q97TZ6

### ISSUE THREAD

**Issue by mugitty** [pantherdb/features-bugs#14]
I noticed that if I search for 'coBs' in pantherdb.org, the system will indicate that there are associated genes.  Clicking to view set of associated genes will bring up System error page.

SACS2|EnsemblGenome=SSO3234|UniProtKB=Q97TZ6 is missing species, protein and source_id in gene aggregation table.

This gene occurs in family PTHR34148.

Attempting to parse the protein information for the gene results in exception in code.

**Comment by dustine32** [comment]
This might be due to the the 5-letter species code change (SULSO -> SACS2) in this version. I just fixed this in the `organism` table but probably need to regenerate the `genelist_agg` view to fix.

**Comment by mugitty** [comment]
@dustine32  has fixed with UPL16 build
