### ISSUE TITLE
Flatten IBA propagator XML output and add addtl values for each node

### ISSUE THREAD

**Issue by dustine32** [pantherdb/features-bugs#20]
Currently the XML output of the PAINT tool propagator contains the family tree structure that needs to be traversed to grab all leaf IBA annotations for converting to IBA GAF. It also contains IBAs to internal nodes, which we wouldn't need to output in the GAFs.

Here's my wishlist for this ticket:
1. Flatten tree structure and only include leaf IBA annotations/nodes
2. Include values rather than DB IDs for select fields.

In the end, we're trying to get from the XML output to a GAF line like this:
```
UniProtKB       E3KUW4  PGTG_12511              GO:0000032      PMID:21873635   IBA     PANTHER:PTN001579360|SGD:S000001769|CGD:CAL0000188769|SGD:S000002891|CGD:CAL0000179131|SGD:S000003675|UniProtKB:A0A1D8PH51      P       Uncharacterized protein UniProtKB:E3KUW4|PTN001258811   protein taxon:418459    20200809        GO_Central
```

Here's an example set of leaf IBA and ancestor IBD nodes from the output file `PTHR31121.xml` corresponding with the IBA in the GAF line above:

**Leaf IBA**
```
<node>
    <persistent_id>PTN001258811</persistent_id>
    <annotation_list>
        <annotation>
            <annotation_id>TEMP_ID_16</annotation_id>
            <evidence_code>IBA</evidence_code>
            <term>GO:0000032</term>
            <paint_direct>false</paint_direct>
            <evidence_list>
                <with_annotation>190600644</with_annotation>
            </evidence_list>
        </annotation>
    </annotation_list>
</node>
```
In this leaf node `<annotation>` we have the GO term (GO:0000032), evidence code (IBA), and leaf node PTN (PTN001258811) that we can use in the GAF line. It would be great to also add in:
* Gene symbol - PGTG_12511
* Gene name - Uncharacterized protein
* Taxon ID - 418459
* Gene product ID - UniProtKB:E3KUW4 (or UniProtKB and E3KUW4 in separate fields)
  * Whether we use the UniProtKB or MOD identifier here is tied to complex logic in the current [createGAF.pl script](https://github.com/pantherdb/fullgo_paint_update/blob/64a7fc90601f2ba9b995e5161921ce4979efecb7/scripts/createGAF.pl#L183-L226) so maybe just supply the full long ID?

**Ancestor IBD**
```
<node>
    <persistent_id>PTN001579360</persistent_id>
    <annotation_list>
        <annotation>
            <annotation_id>190600644</annotation_id>
            <evidence_code>IBD</evidence_code>
            <term>GO:0000032</term>
            <paint_direct>true</paint_direct>
            <evidence_list>
                <with_annotation>660991577</with_annotation>
                <with_annotation>386033385</with_annotation>
                <with_annotation>749555095</with_annotation>
                <with_annotation>749779322</with_annotation>
                <with_annotation>386033386</with_annotation>
                <with_annotation>386033389</with_annotation>
            </evidence_list>
        </annotation>
    </annotation_list>
</node>
```
This node already contains the IBD PTN (PTN001579360) but we'll still need the IBD creation_date (20200809 in any format) as well as all of the GP IDs tied to those `with_annotation` DB IDs. I think you could just use the GP long IDs here as well.

Here's my ideal `<annotation>` IBA node for this example:
```
<node>
    <persistent_id>PTN001258811</persistent_id>
    <annotation_list>
        <annotation>
            <annotation_id>TEMP_ID_16</annotation_id>
            <gene_long_id>PUCGT|EnsemblGenome=PGTG_12511|UniProtKB=E3KUW4</gene_long_id>
            <gene_name>Uncharacterized protein</gene_name>
            <gene_symbol>PGTG_12511</gene_symbol>
            <evidence_code>IBA</evidence_code>
            <taxon_id>418459</taxon_id>
            <term>GO:0000032</term>
            <qualifier>NOT</qualifier>
            <paint_direct>false</paint_direct>
            <evidence_list>
                <with_annotation>
                    <annotation_id>190600644</annotation_id>
                    <creation_date>20200809</creation_date>
                    <evidence_code>IBD</evidence_code>
                    <persistent_id>PTN001579360</persistent_id>
                    <with>
                        <gene_long_id>CANAL|CGD=CAL0000179131|UniProtKB=Q59QH4</gene_long_id>
                        <gene_long_id>YEAST|SGD=S000003675|UniProtKB=P26725</gene_long_id>
                        <gene_long_id>YEAST|SGD=S000001769|UniProtKB=P33550</gene_long_id>
                        <gene_long_id>CANAL|Gene_ORFName=CAALFM_C204560WA|UniProtKB=A0A1D8PH51</gene_long_id>
                        <gene_long_id>YEAST|SGD=S000002891|UniProtKB=P27809</gene_long_id>
                        <gene_long_id>CANAL|CGD=CAL0000188769|UniProtKB=P87207</gene_long_id>
                    </with>
                </with_annotation>
            </evidence_list>
        </annotation>
    </annotation_list>
</node>
```

Don't fret on getting any of the values requested if the required changes will slow down the propagator job since I can likely get these values from other flat file data sources. But I'm just trying to keep the XML-to-GAF formatter simple. Thanks!

Edit NOTE: Added qualifier example to desired XML.

**Comment by mugitty** [comment]
@dustine32, annotation creation date should be added to go_aggregate table .  I will let you know when to add.

The rest of the requests should be easy to fill. We may need to cut back on some of these, if performance becomes an issue.

**Comment by dustine32** [comment]
@mugitty Great, thanks for the feedback! Adding `creation_date` to `go_aggregate` shouldn't be a problem. I'll make a ticket in https://github.com/pantherdb/fullgo_paint_update to update the view generation script.

And yeah, just lemme know as you work through these fields what data you think would be more efficient if I just sourced them from elsewhere.

**Comment by mugitty** [comment]
@dustine32 , do you want all leaves or only those that provide evidence for PAINT annotations and also those that get IBA annotations? There are some leaves that may or may not have experimental evidence  and also do not get propagated IBA's

**Comment by dustine32** [comment]
@mugitty I would only need the leaf nodes that get IBA annotations.

**Comment by dustine32** [comment]
For IBA-from-IKR cases, here's an example GAF line I would create:
```
CGD   CAL0000182821   TPS1    NOT     GO:0070413      PMID:21873635   IBA   PANTHER:PTN000846181|PANTHER:PTN000846179       P       Alpha,alpha-trehalose-phosphate synthase [UDP-forming]  UniProtKB:Q92410|PTN000846256   protein taxon:237561    20181001        GO_Central
```
Given this desired XML below:
```
<node>
    <persistent_id>PTN000846256</persistent_id>
    <annotation_list>
        <annotation>
            <annotation_id>TEMP_ID_16</annotation_id>
            <gene_long_id>CANAL|CGD=CAL0000182821|UniProtKB=Q92410</gene_long_id>
            <gene_name>Alpha,alpha-trehalose-phosphate synthase [UDP-forming]</gene_name>
            <gene_symbol>TPS1</gene_symbol>
            <evidence_code>IBA</evidence_code>
            <taxon_id>237561</taxon_id>
            <term>GO:0070413</term>
            <qualifier>NOT</qualifier>
            <paint_direct>false</paint_direct>
            <evidence_list>
                <with_annotation>
                    <annotation_id>194493090</annotation_id>
                    <creation_date>20181001</creation_date>
                    <evidence_code>IKR</evidence_code>
                    <persistent_id>PTN000846181</persistent_id>
                    <with>
                        <persistent_id>PTN000846179</persistent_id>
                        <evidence_code>IBD</evidence_code>
                    </with>
                </with_annotation>
            </evidence_list>
        </annotation>
    </annotation_list>
</node>
```

**Comment by dustine32** [comment]
@mugitty Also, I think a correction about the `creation_date` field. This field should be added to the `paint_aggregate` view rather than `go_aggregate` since we want the `creation_date` of the PAINT annotation. Does this sound right?

**Comment by mugitty** [comment]
@dustine32 , we need the date in go_aggregate.  paint_aggregate is not used by the GAF generation code.  I will modify the code that retrieves the paint annotation to also retrieve the creation date.

**Comment by dustine32** [comment]
@mugitty OK, thanks! I will leave `creation_date` in the `go_aggregate` generation script.

**Comment by mugitty** [comment]
@dustine32, thanks.  I will let you know once I have generated data for some sample books

**Comment by mugitty** [comment]
@dustine32 , I need the creation date in the paint_aggregate table in addition to the go_aggregation table for the script that generates information on just the aggregation table.

**Comment by dustine32** [comment]
Great! I am lazy so I left `creation_date` in both tables.

**Comment by mugitty** [comment]
Thanks!
